In [1]:
import pandas as pd

In [2]:
generation_df = pd.read_csv(r'C:\Users\pc\Downloads\Energy_Access_&_Electrification_Planning_in_Africa\electricity_generation_demand\electricity-generation.csv')
generation_df

             Entity Code  Year  Electricity generation - TWh
0     ASEAN (Ember)  NaN  2000                        378.61
1     ASEAN (Ember)  NaN  2001                        404.85
2     ASEAN (Ember)  NaN  2002                        433.19
3     ASEAN (Ember)  NaN  2003                        458.24
4     ASEAN (Ember)  NaN  2004                        496.56
...             ...  ...   ...                           ...
7407       Zimbabwe  ZWE  2018                          9.44
7408       Zimbabwe  ZWE  2019                          8.49
7409       Zimbabwe  ZWE  2020                          6.71
7410       Zimbabwe  ZWE  2021                          8.46
7411       Zimbabwe  ZWE  2022                          8.93

[7412 rows x 4 columns]

In [3]:
demand_df = pd.read_csv(r'C:\Users\pc\Downloads\Energy_Access_&_Electrification_Planning_in_Africa\electricity_generation_demand\electricity-demand.csv')
demand_df

             Entity Code  Year  Electricity demand - TWh
0     ASEAN (Ember)  NaN  2000                    378.61
1     ASEAN (Ember)  NaN  2001                    404.85
2     ASEAN (Ember)  NaN  2002                    433.19
3     ASEAN (Ember)  NaN  2003                    458.24
4     ASEAN (Ember)  NaN  2004                    496.56
...             ...  ...   ...                       ...
5858       Zimbabwe  ZWE  2018                     10.46
5859       Zimbabwe  ZWE  2019                      9.60
5860       Zimbabwe  ZWE  2020                      8.69
5861       Zimbabwe  ZWE  2021                     10.20
5862       Zimbabwe  ZWE  2022                     10.69

[5863 rows x 4 columns]

In [4]:
africa_df = pd.read_excel(r'C:\Users\pc\Downloads\Energy_Access_&_Electrification_Planning_in_Africa\electricity_generation_demand\african_countries.xlsx')
africa_df

                           Countries           Region
0                            Algeria  Northern Africa
1                              Egypt  Northern Africa
2                              Libya  Northern Africa
3                            Morocco  Northern Africa
4                              Sudan  Northern Africa
5                            Tunisia  Northern Africa
6                              Benin   Western Africa
7                       Burkina Faso   Western Africa
8                         Cape Verde   Western Africa
9        Côte d'Ivoire (Ivory Coast)   Western Africa
10                            Gambia   Western Africa
11                             Ghana   Western Africa
12                            Guinea   Western Africa
13                     Guinea-Bissau   Western Africa
14                           Liberia   Western Africa
15                              Mali   Western Africa
16                             Niger   Western Africa
17                           Nigeria   Western Africa
18                           Senegal   Western Africa
19                      Sierra Leone   Western Africa
20                        Mauritania   Western Africa
21                              Togo   Western Africa
22                           Burundi   Eastern Africa
23                          Djibouti   Eastern Africa
24                           Eritrea   Eastern Africa
25                          Ethiopia   Eastern Africa
26                             Kenya   Eastern Africa
27                        Madagascar   Eastern Africa
28                         Mauritius   Eastern Africa
29                            Rwanda   Eastern Africa
30                        Seychelles   Eastern Africa
31                           Somalia   Eastern Africa
32                       South Sudan   Eastern Africa
33                          Tanzania   Eastern Africa
34                           Comoros   Eastern Africa
35                            Uganda   Eastern Africa
36                            Angola   Central Africa
37                          Cameroon   Central Africa
38          Central African Republic   Central Africa
39                              Chad   Central Africa
40  Democratic Republic of the Congo   Central Africa
41             Republic of the Congo   Central Africa
42                 Equatorial Guinea   Central Africa
43                             Gabon   Central Africa
44             São Tomé and Príncipe   Central Africa
45                          Botswana  Southern Africa
46                          Eswatini  Southern Africa
47                           Lesotho  Southern Africa
48                           Namibia  Southern Africa
49                      South Africa  Southern Africa
50                            Zambia  Southern Africa
51                          Zimbabwe  Southern Africa
52                            Malawi  Southern Africa
53                        Mozambique  Southern Africa